version: 2
jobs:
# asb-e2e:
#   machine: true
#   steps:
#     - checkout
#     - run: ./.circleci/asb.sh
#
  voting-orbs-tests:
    docker:
      - image: circleci/golang:1.12.9
    steps:
      - checkout
      - run: cd voting/orbs && ./test.sh
      - store_artifacts:
          path: voting/orbs/_out
      - store_test_results:
          path: voting/orbs/_out

  voting-solidity-tests:
    docker:
      - image: circleci/node:11.2.0
    steps:
      - checkout
      - run: cd voting/ethereum && ./test.sh
      - store_artifacts:
          path: voting/ethereum/_out
      - store_test_results:
          path: voting/ethereum/_reports

  voting-client-tests:
    docker:
      - image: circleci/node:11.2.0
    steps:
      - checkout
      - run: cd voting/client-web && npm install && npm run test:ci
      - store_test_results:
          path: voting/client-web/_reports

  voting-e2e:
    machine: true
    steps:
      - checkout
      - run: ./.circleci/voting.sh
      - store_artifacts:
          path: _out
          destination: test-output
      - store_test_results:
          path: _out

  subscription-e2e:
    machine: true
    steps:
      - checkout
      - run: ./.circleci/subscription.sh
      - store_artifacts:
          path: _out
          destination: test-output

  subscription-solidity-tests:
    docker:
      - image: circleci/node:11.2.0
    steps:
      - checkout
      - run: cd subscription/ethereum && ./test.sh
      - store_artifacts:
          path: subscription/ethereum/_out
      - store_test_results:
          path: subscription/ethereum/_reports

  rewards-distribution-solidity-tests:
    docker:
      - image: circleci/node:11.2.0
    steps:
      - checkout
      - run: cd rewards-distribution/ethereum && ./test.sh
      - store_artifacts:
          path: rewards-distribution/ethereum/_out
      - store_test_results:
          path: rewards-distribution/ethereum/_reports

workflows:
  version: 2
  voting:
    jobs:
      - voting-solidity-tests
      - voting-orbs-tests
      - voting-client-tests
      - voting-e2e
  subscription:
    jobs:
      - subscription-solidity-tests
      - subscription-e2e
  rewards-distribution:
    jobs:
      - rewards-distribution-solidity-tests
  nightly:
    triggers:
      - schedule:
          cron: "0 23 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      # tests that integrate with orbs-network-go
      - subscription-e2e
      - voting-orbs-tests
      - voting-e2e
        requires:
        - voting-orbs-tests
